Throw UnsupportedOpenAPISpec when openAPI version is not 3.x.x
sennder/python-client-generator pull request #10
Opened 2023-05-04 20:39 UTC by damey2011

The current implementation does not specify the supported openAPI spec versions. This MR:

- Documents that it supports version 3.x.x
- Throws an error when openAPI spec of non 3.x.x is provided

2023-05-04 21:06 UTC, bogdanp05 requested changes
Thanks for the MR! Looks good, just 2 minor things.

I don't fully get why the pipeline didn't run, probably because it's coming from a fork? Anyways, you'll have to change the last commit message to smth like "test: ..." so it passes commitlint.

2023-05-04 21:06 UTC, bogdanp05 commented on .github/CONTRIBUTING.md
> +This project was developed using Python3.8, other python version have not been fully tested.
Can you replace this with "older Python versions..."? In the pipeline we do have tests for 3.9 and 3.10.

2023-05-04 21:06 UTC, bogdanp05 commented on README.md
> +> :warning: **Currently does not support OpenAPI 2.0**: MR for < 3.0 support are welcome
MRs*

2023-05-04 22:30 UTC, damey2011 commented on .github/CONTRIBUTING.md
> +This project was developed using Python3.8, other python version have not been fully tested.
Okay.. But for some reasons `poetry install` fails while installing `typed-ast` with python3.9 and 3.10 for me.

```
  PoetryException

  Failed to install /Users/theoluwanifemi/Library/Caches/pypoetry/artifacts/cc/50/4d/e1b50dadd10f8d3f8bd6f6c2e764cf988f0e86c4047c0210353ba77680/typed_ast-1.4.3.tar.gz

  at ~/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/poetry/utils/pip.py:58 in pip_install
       54│ 
       55│     try:
       56│         return environment.run_pip(*args)
       57│     except EnvCommandError as e:
    →  58│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       59│ 


```

2023-05-04 22:32 UTC, damey2011 commented on README.md
> +> :warning: **Currently does not support OpenAPI 2.0**: MR for < 3.0 support are welcome
Fixed.

2023-05-05 10:21 UTC, bogdanp05 commented on .github/CONTRIBUTING.md
> +This project was developed using Python3.8, other python version have not been fully tested.
That's weird. I tried just now with python 3.10.9 and it worked. And it does work in the [pipeline](https://github.com/sennder/python-client-generator/blob/main/.github/workflows/cicd.yml#L23).

2023-05-05 10:21 UTC, merged